version: "3.4"

# Development environment override
services:
  php:
    platform: linux/amd64
    build:
      context: app
      target: php_dev
      dockerfile: ../docker/Dockerfile
      args:
        PHP_VERSION: "${PHP_VERSION:-7.4}"
    volumes:
      - ./:/srv/app
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      - host.docker.internal:host-gateway
