services:
    php-fpm:
        #    platform: linux/amd64
        build:
            context: docker
            target: php_dev
            dockerfile: ../docker/php/Dockerfile
        command: php-fpm
        volumes:
            - ./app:/srv/app
        environment:
            XDEBUG_MODE: "${XDEBUG_MODE:-off}"
            PHP_IDE_CONFIG: "serverName=app.localhost"
        restart: unless-stopped

    httpd:
        build:
            context: docker
            dockerfile: ../docker/httpd/Dockerfile
        volumes:
            - ./app:/srv/app
        ports:
            - "8080:80"
            - "4430:443"
        links:
            - php-fpm

    dozzle:
        image: amir20/dozzle:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            DOZZLE_LEVEL: debug
            DOZZLE_USERNAME_FILE: /run/secrets/dozzle_user
            DOZZLE_PASSWORD_FILE: /run/secrets/dozzle_password
        secrets:
            - dozzle_user
            - dozzle_password
        ports:
            - 9999:8080

    adminer:
        #    hostname: adminer
        image: adminer
        environment:
            ADMINER_DEFAULT_SERVER: mariadb
            ADMINER_DESIGN: pepa-linha-dark
        ports:
            - "8200:8080"

    db:
        image: mariadb:${MARIADB_VERSION:-11.1.2}
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_PORT-41003}:3306

secrets:
    dozzle_user:
        file: secrets/dozzle_user
    dozzle_password:
        file: secrets/dozzle_password



