services:
  php-fpm:
    build:
      context: ./docker
      args:
         :
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - '.:/application'
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
      test: ["CMD", "curl", "-f", "http://localhost"]
    environment:
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
    depends_on:
      - database

  database:
    image: mariadb:${MARIADB_VERSION:-11.1.2}
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT-41003}:3306

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: database
      MEMORY_LIMIT: ${PMA_MEMORY_LIMIT}
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT}
    ports:
      - '${PMA_PORT}:80'
    depends_on:
      - database

volumes:
  php_socket:
